#ifndef ORB_LED_SCENES_H
#define ORB_LED_SCENES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Shared LED scene identifiers used across modes and LED service.
 * Keep this table as single source of truth for scene numeric IDs.
 */
#define ORB_LED_SCENE_ID_IDLE_BREATHE UINT32_C(1)
#define ORB_LED_SCENE_ID_TOUCH_AWAKE UINT32_C(2)
#define ORB_LED_SCENE_ID_ERROR_FLASH UINT32_C(3)
#define ORB_LED_SCENE_ID_FIRE2012 UINT32_C(4)
#define ORB_LED_SCENE_ID_PLASMA UINT32_C(5)
#define ORB_LED_SCENE_ID_SPARKLE UINT32_C(6)
#define ORB_LED_SCENE_ID_COLOR_WAVE UINT32_C(7)
#define ORB_LED_SCENE_ID_AURA_COLOR_BREATHE UINT32_C(8)
#define ORB_LED_SCENE_ID_GRUMBLE_RED UINT32_C(9)
#define ORB_LED_SCENE_ID_LOTTERY_IDLE UINT32_C(10)
#define ORB_LED_SCENE_ID_LOTTERY_HOLD_RAMP UINT32_C(11)
#define ORB_LED_SCENE_ID_HYBRID_IDLE_SLOW_BREATHE UINT32_C(12)
#define ORB_LED_SCENE_ID_HYBRID_TOUCH_FAST_BREATHE UINT32_C(13)
#define ORB_LED_SCENE_ID_HYBRID_VORTEX UINT32_C(14)
#define ORB_LED_SCENE_ID_HYBRID_VORTEX_DIM UINT32_C(15)

#ifdef __cplusplus
}
#endif

#endif
