#ifndef ORB_LED_SCENES_H
#define ORB_LED_SCENES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Shared LED scene identifiers used across modes and LED service.
 * Keep this table as single source of truth for scene numeric IDs.
 */
#define ORB_LED_SCENE_ID_IDLE_BREATHE UINT32_C(1)
#define ORB_LED_SCENE_ID_TOUCH_AWAKE UINT32_C(2)
#define ORB_LED_SCENE_ID_ERROR_FLASH UINT32_C(3)
#define ORB_LED_SCENE_ID_FIRE2012 UINT32_C(4)
#define ORB_LED_SCENE_ID_PLASMA UINT32_C(5)
#define ORB_LED_SCENE_ID_SPARKLE UINT32_C(6)
#define ORB_LED_SCENE_ID_COLOR_WAVE UINT32_C(7)
#define ORB_LED_SCENE_ID_AURA_COLOR_BREATHE UINT32_C(8)
#define ORB_LED_SCENE_ID_GRUMBLE_RED UINT32_C(9)
#define ORB_LED_SCENE_ID_LOTTERY_IDLE UINT32_C(10)
#define ORB_LED_SCENE_ID_LOTTERY_HOLD_RAMP UINT32_C(11)
#define ORB_LED_SCENE_ID_HYBRID_IDLE_SLOW_BREATHE UINT32_C(12)
#define ORB_LED_SCENE_ID_HYBRID_TOUCH_FAST_BREATHE UINT32_C(13)
#define ORB_LED_SCENE_ID_HYBRID_VORTEX UINT32_C(14)
#define ORB_LED_SCENE_ID_HYBRID_VORTEX_DIM UINT32_C(15)
#define ORB_LED_SCENE_ID_HYBRID_WLED_METABALLS UINT32_C(16)
#define ORB_LED_SCENE_ID_HYBRID_WLED_DNA UINT32_C(17)
#define ORB_LED_SCENE_ID_HYBRID_WLED_TWISTER UINT32_C(18)
#define ORB_LED_SCENE_ID_HYBRID_WLED_CHECKER_PULSE UINT32_C(19)
#define ORB_LED_SCENE_ID_HYBRID_WLED_RAIN UINT32_C(20)
#define ORB_LED_SCENE_ID_HYBRID_WLED_RADIAL_BURST UINT32_C(21)
#define ORB_LED_SCENE_ID_HYBRID_WLED_TUNNEL UINT32_C(22)
#define ORB_LED_SCENE_ID_HYBRID_WLED_BANDS UINT32_C(23)
#define ORB_LED_SCENE_ID_HYBRID_WLED_STARFIELD UINT32_C(24)
#define ORB_LED_SCENE_ID_HYBRID_WLED_CONFETTI UINT32_C(25)
#define ORB_LED_SCENE_ID_HYBRID_WLED_LAVA UINT32_C(26)
#define ORB_LED_SCENE_ID_HYBRID_WLED_RINGS UINT32_C(27)
#define ORB_LED_SCENE_ID_HYBRID_WLED_NOISE UINT32_C(28)
#define ORB_LED_SCENE_ID_HYBRID_WLED_SCANNER UINT32_C(29)
#define ORB_LED_SCENE_ID_HYBRID_WLED_ZIGZAG UINT32_C(30)
#define ORB_LED_SCENE_ID_HYBRID_WLED_AURORA UINT32_C(31)
#define ORB_LED_SCENE_ID_HYBRID_WLED_PRISM UINT32_C(32)
#define ORB_LED_SCENE_ID_HYBRID_WLED_CLOUDS UINT32_C(33)
#define ORB_LED_SCENE_ID_HYBRID_WLED_WAVEGRID UINT32_C(34)
#define ORB_LED_SCENE_ID_HYBRID_WLED_HEARTBEAT UINT32_C(35)
#define ORB_LED_SCENE_ID_HYBRID_WLED_PINWHEEL UINT32_C(36)
#define ORB_LED_SCENE_ID_HYBRID_WLED_COMET UINT32_C(37)

#ifdef __cplusplus
}
#endif

#endif
