#ifndef BSP_PINS_H
#define BSP_PINS_H

#include "sdkconfig.h"

#define BSP_BOARD_LED_GPIO CONFIG_ORB_BOARD_LED_GPIO
#define BSP_STATUS_GPIO CONFIG_ORB_STATUS_GPIO
#define BSP_LED_DATA_GPIO CONFIG_ORB_LED_DATA_GPIO
#define BSP_AMP_ENABLE_GPIO CONFIG_ORB_AMP_ENABLE_GPIO
#define BSP_MODE_BUTTON_GPIO CONFIG_ORB_MODE_BUTTON_GPIO

#endif
