#ifndef AUDIO_TYPES_H
#define AUDIO_TYPES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    AUDIO_ASSET_NONE = 0,
    AUDIO_ASSET_STARTUP_CHIME = 1,
    AUDIO_ASSET_ACK = 2,
    AUDIO_ASSET_ERROR = 3,
    AUDIO_ASSET_LOTTERY_SORTING = 1101,
    AUDIO_ASSET_LOTTERY_TEAM1 = 1102,
    AUDIO_ASSET_LOTTERY_TEAM2 = 1103,
    AUDIO_ASSET_LOTTERY_TEAM3 = 1104,
    AUDIO_ASSET_LOTTERY_TEAM4 = 1105,
    AUDIO_ASSET_LOTTERY_FINISHED = 1106,
    AUDIO_ASSET_PROPHECY_GREET_CHOICE = 1201,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_CHOICE = 1202,
    AUDIO_ASSET_PROPHECY_PREDICTION_CHOICE = 1203,
    AUDIO_ASSET_PROPHECY_FAREWELL_CHOICE = 1204,
    AUDIO_ASSET_PROPHECY_GREET_DANGER = 1205,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_DANGER = 1206,
    AUDIO_ASSET_PROPHECY_PREDICTION_DANGER = 1207,
    AUDIO_ASSET_PROPHECY_FAREWELL_DANGER = 1208,
    AUDIO_ASSET_PROPHECY_GREET_FUTURE = 1209,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_FUTURE = 1210,
    AUDIO_ASSET_PROPHECY_PREDICTION_FUTURE = 1211,
    AUDIO_ASSET_PROPHECY_FAREWELL_FUTURE = 1212,
    AUDIO_ASSET_PROPHECY_GREET_INNER_STATE = 1213,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_INNER_STATE = 1214,
    AUDIO_ASSET_PROPHECY_PREDICTION_INNER_STATE = 1215,
    AUDIO_ASSET_PROPHECY_FAREWELL_INNER_STATE = 1216,
    AUDIO_ASSET_PROPHECY_GREET_LOVE = 1217,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_LOVE = 1218,
    AUDIO_ASSET_PROPHECY_PREDICTION_LOVE = 1219,
    AUDIO_ASSET_PROPHECY_FAREWELL_LOVE = 1220,
    AUDIO_ASSET_PROPHECY_GREET_LUCK = 1221,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_LUCK = 1222,
    AUDIO_ASSET_PROPHECY_PREDICTION_LUCK = 1223,
    AUDIO_ASSET_PROPHECY_FAREWELL_LUCK = 1224,
    AUDIO_ASSET_PROPHECY_GREET_MONEY = 1225,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_MONEY = 1226,
    AUDIO_ASSET_PROPHECY_PREDICTION_MONEY = 1227,
    AUDIO_ASSET_PROPHECY_FAREWELL_MONEY = 1228,
    AUDIO_ASSET_PROPHECY_GREET_WISH = 1229,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_WISH = 1230,
    AUDIO_ASSET_PROPHECY_PREDICTION_WISH = 1231,
    AUDIO_ASSET_PROPHECY_FAREWELL_WISH = 1232,
    AUDIO_ASSET_PROPHECY_GREET_YES_NO = 1233,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_YES_NO = 1234,
    AUDIO_ASSET_PROPHECY_PREDICTION_YES_NO = 1235,
    AUDIO_ASSET_PROPHECY_FAREWELL_YES_NO = 1236,
    AUDIO_ASSET_PROPHECY_GREET_TIMING = 1237,
    AUDIO_ASSET_PROPHECY_UNDERSTANDING_TIMING = 1238,
    AUDIO_ASSET_PROPHECY_PREDICTION_TIMING = 1239,
    AUDIO_ASSET_PROPHECY_FAREWELL_TIMING = 1240,
    AUDIO_ASSET_HYBRID_START_PHRASE = 1301,
    /* Service phrase assets for explicit hybrid prompts. */
    AUDIO_ASSET_HYBRID_RETRY_PHRASE = 1302,
    AUDIO_ASSET_HYBRID_FAIL_PHRASE = 1303,
    AUDIO_ASSET_HYBRID_JOKE_PHRASE = 1304,
    AUDIO_ASSET_HYBRID_FORBIDDEN_PHRASE = 1305,
    AUDIO_ASSET_DYNAMIC_SLOT1 = 1001,
    AUDIO_ASSET_DYNAMIC_SLOT2 = 1002,
} audio_asset_id_t;

/* Canonical naming: "path" uses the former "luck" asset ID range. */
#define AUDIO_ASSET_PROPHECY_GREET_PATH AUDIO_ASSET_PROPHECY_GREET_LUCK
#define AUDIO_ASSET_PROPHECY_UNDERSTANDING_PATH AUDIO_ASSET_PROPHECY_UNDERSTANDING_LUCK
#define AUDIO_ASSET_PROPHECY_PREDICTION_PATH AUDIO_ASSET_PROPHECY_PREDICTION_LUCK
#define AUDIO_ASSET_PROPHECY_FAREWELL_PATH AUDIO_ASSET_PROPHECY_FAREWELL_LUCK
/* Canonical naming: "timing" is the archetype for time questions. */
#define AUDIO_ASSET_PROPHECY_GREET_TIME AUDIO_ASSET_PROPHECY_GREET_TIMING
#define AUDIO_ASSET_PROPHECY_UNDERSTANDING_TIME AUDIO_ASSET_PROPHECY_UNDERSTANDING_TIMING
#define AUDIO_ASSET_PROPHECY_PREDICTION_TIME AUDIO_ASSET_PROPHECY_PREDICTION_TIMING
#define AUDIO_ASSET_PROPHECY_FAREWELL_TIME AUDIO_ASSET_PROPHECY_FAREWELL_TIMING

typedef enum {
    AUDIO_PLAYBACK_IDLE = 0,
    AUDIO_PLAYBACK_PLAYING,
    AUDIO_PLAYBACK_STOPPING,
} audio_playback_state_t;

#ifdef __cplusplus
}
#endif

#endif
